name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build the Docker image
      run: |
       docker build . --file Dockerfile --tag simple-html-page:latest

    - name: List Docker images (debugging)
      run: docker images

    - name: Run docker container
      run: docker run -d -p 80:80 simple-html-page:latest

